<a href="https://colab.research.google.com/github/fahd-sherif/ITI/blob/main/probability_and_statistic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
ages=[18,21,20,19,22,23,20,21,22,19]
manual_mean=sum(ages)/len(ages)
print(manual_mean)
numpy_mean=np.mean(ages)
print(numpy_mean)

20.5
20.5


In [ ]:
my_list=np.random.randint(10,51,15)
print(my_list)
sort_list=np.sort(my_list)
print(sort_list)
print(sort_list[7])
list_median=np.median(my_list)
print(list_median)

[39 37 36 22 24 28 37 30 22 47 40 28 41 38 19]
[19 22 22 24 28 28 30 36 37 37 38 39 40 41 47]
36
36.0


In [ ]:
my_list=np.random.randint(10,51,15)
print(my_list)
sort_list=np.sort(my_list)
print(sort_list)
print(np.minimum(sort_list[0],sort_list[14]))
print(np.maximum(sort_list[0],sort_list[14]))
range=np.maximum(sort_list[0],sort_list[14])-np.minimum(sort_list[0],sort_list[14])
print(range)
range_numpy=np.ptp(my_list)
print(range_numpy)

[47 26 24 32 13 25 16 13 20 19 25 38 43 30 36]
[13 13 16 19 20 24 25 25 26 30 32 36 38 43 47]
13
47
34
34


In [ ]:
data = [5, 7, 3, 7, 9, 10, 15, 7]
mean = sum(data) / len(data)
squared_diffs = [(x - mean) ** 2 for x in data]
variance = sum(squared_diffs) / len(data)
std_dev = variance ** 0.5
print("Variance:", variance)
print("Standard Deviation:",std_dev)
#with numpy
variance = np.var(data)
std_dev = np.std(data)
print("Variance:", variance)
print("Standard Deviation:",std_dev)

Variance: 11.359375
Standard Deviation: 3.370367190678191
Variance: 11.359375
Standard Deviation: 3.370367190678191


In [3]:
data = [5, 7, 3, 7, 9, 10, 15, 7]
q1 = np.percentile(data, 25)
q2 = np.percentile(data, 50)
q3 = np.percentile(data, 75)
iqr = q3 - q1
print("Q1 =", q1)
print("Q2 (median) =", q2)
print("Q3 =", q3)
print("IQR =",iqr)

Q1 = 6.5
Q2 (median) = 7.0
Q3 = 9.25
IQR = 2.75


In [5]:
data = [10, 20, 30, 40, 50]
mean = sum(data) / len(data)
variance = sum((x - mean) ** 2 for x in data) / len(data)
std_dev = variance ** 0.5
z_scores = [(x - mean) / std_dev for x in data]
print("Z-scores:", z_scores)

Z-scores: [-1.414213562373095, -0.7071067811865475, 0.0, 0.7071067811865475, 1.414213562373095]


In [9]:
import random
import numpy as np
data = [random.randint(1, 100) for _ in range(20)]
print("Data:", data)
#Moving average using list slicing
window_size = 3
moving_avg_slicing = [
    sum(data[i:i+window_size]) / window_size
    for i in range(len(data) - window_size + 1)]
print("Moving Average (list slicing):", moving_avg_slicing)
weights = np.ones(window_size) / window_size
#Compare with numpy.convolve().
moving_avg_convolve = np.convolve(data, weights, mode='valid')
print("(numpy.convolve):", moving_avg_convolve.tolist())
comparison = all(
    abs(a - b) < 1e-9 for a, b in zip(moving_avg_slicing, moving_avg_convolve))
print("Results:",comparison)

Data: [73, 50, 67, 99, 87, 69, 14, 99, 95, 64, 40, 20, 3, 33, 2, 58, 9, 19, 81, 8]
Moving Average (list slicing): [63.333333333333336, 72.0, 84.33333333333333, 85.0, 56.666666666666664, 60.666666666666664, 69.33333333333333, 86.0, 66.33333333333333, 41.333333333333336, 21.0, 18.666666666666668, 12.666666666666666, 31.0, 23.0, 28.666666666666668, 36.333333333333336, 36.0]
(numpy.convolve): [63.33333333333333, 72.0, 84.33333333333333, 85.0, 56.666666666666664, 60.666666666666664, 69.33333333333333, 85.99999999999999, 66.33333333333333, 41.33333333333333, 21.0, 18.666666666666664, 12.666666666666666, 31.0, 23.0, 28.666666666666664, 36.33333333333333, 36.0]
Results: True


In [24]:
numbers = np.random.randint(1, 51, 25)
numbers =np.append(numbers,(300,400))
print(numbers)
q1 = np.percentile(numbers, 25)
q2 = np.percentile(numbers, 50)
q3 = np.percentile(numbers, 75)
iqr = q3 - q1
print("Q1 =", q1)
print("Q2 (median) =", q2)
print("Q3 =", q3)
print("IQR =",iqr)
Upper = q3 + 1.5 * iqr
Lower = q1 - 1.5 * iqr
print("Upper bound:", Upper)
print("Lower bound:", Lower)
outliers= []
for x in numbers:
    if x > Upper:
        outliers.append(x)
    if x < Lower:
        outliers.append(x)
print("Outliers:", outliers)

[ 13  24   7  41  14  45  15   5  30  18  45  20  25  41  28  25  43   7
  29   6   9  47  30   1   8 300 400]
Q1 = 11.0
Q2 (median) = 25.0
Q3 = 41.0
IQR = 30.0
Upper bound: 86.0
Lower bound: -34.0
Outliers: [np.int64(300), np.int64(400)]
